/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FinalDedication { 'title' : string, 'message' : string }
export interface FlipCard { 'front' : string, 'back' : string }
export interface GalleryItem {
  'id' : string,
  'order' : bigint,
  'caption' : string,
  'image' : ExternalBlob,
}
export interface InteractiveSurpriseConfig {
  'quizQuestions' : Array<QuizQuestion>,
  'flipCards' : Array<FlipCard>,
}
export interface LoveMessage {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'preview' : string,
  'fullText' : string,
}
export interface QuizQuestion {
  'question' : string,
  'correctAnswer' : string,
  'options' : Array<string>,
}
export type Time = bigint;
export interface TimelineMilestone {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'date' : Time,
  'description' : string,
  'photo' : [] | [ExternalBlob],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryItem' : ActorMethod<
    [string, ExternalBlob, string, bigint],
    undefined
  >,
  'addLoveMessage' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'addTimelineMilestone' : ActorMethod<
    [string, Time, string, string, [] | [ExternalBlob], bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGalleryItem' : ActorMethod<[string], undefined>,
  'deleteLoveMessage' : ActorMethod<[string], undefined>,
  'deleteTimelineMilestone' : ActorMethod<[string], undefined>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllLoveMessages' : ActorMethod<[], Array<LoveMessage>>,
  'getAllTimelineMilestones' : ActorMethod<[], Array<TimelineMilestone>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFinalDedication' : ActorMethod<[], [] | [FinalDedication]>,
  'getInteractiveSurpriseConfig' : ActorMethod<
    [],
    [] | [InteractiveSurpriseConfig]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setFinalDedication' : ActorMethod<[FinalDedication], undefined>,
  'setInteractiveSurpriseConfig' : ActorMethod<
    [InteractiveSurpriseConfig],
    undefined
  >,
  'updateGalleryItemOrder' : ActorMethod<[string, bigint], undefined>,
  'updateLoveMessage' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateLoveMessageOrder' : ActorMethod<[string, bigint], undefined>,
  'updateTimelineMilestone' : ActorMethod<
    [string, Time, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'updateTimelineMilestoneOrder' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];