/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'caption' : IDL.Text,
  'image' : ExternalBlob,
});
export const LoveMessage = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'preview' : IDL.Text,
  'fullText' : IDL.Text,
});
export const TimelineMilestone = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FinalDedication = IDL.Record({
  'title' : IDL.Text,
  'message' : IDL.Text,
});
export const QuizQuestion = IDL.Record({
  'question' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const FlipCard = IDL.Record({ 'front' : IDL.Text, 'back' : IDL.Text });
export const InteractiveSurpriseConfig = IDL.Record({
  'quizQuestions' : IDL.Vec(QuizQuestion),
  'flipCards' : IDL.Vec(FlipCard),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'addLoveMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'addTimelineMilestone' : IDL.Func(
      [IDL.Text, Time, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
  'deleteLoveMessage' : IDL.Func([IDL.Text], [], []),
  'deleteTimelineMilestone' : IDL.Func([IDL.Text], [], []),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllLoveMessages' : IDL.Func([], [IDL.Vec(LoveMessage)], ['query']),
  'getAllTimelineMilestones' : IDL.Func(
      [],
      [IDL.Vec(TimelineMilestone)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFinalDedication' : IDL.Func([], [IDL.Opt(FinalDedication)], ['query']),
  'getInteractiveSurpriseConfig' : IDL.Func(
      [],
      [IDL.Opt(InteractiveSurpriseConfig)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setFinalDedication' : IDL.Func([FinalDedication], [], []),
  'setInteractiveSurpriseConfig' : IDL.Func(
      [InteractiveSurpriseConfig],
      [],
      [],
    ),
  'updateGalleryItemOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateLoveMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateLoveMessageOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateTimelineMilestone' : IDL.Func(
      [IDL.Text, Time, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateTimelineMilestoneOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'caption' : IDL.Text,
    'image' : ExternalBlob,
  });
  const LoveMessage = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'preview' : IDL.Text,
    'fullText' : IDL.Text,
  });
  const TimelineMilestone = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FinalDedication = IDL.Record({
    'title' : IDL.Text,
    'message' : IDL.Text,
  });
  const QuizQuestion = IDL.Record({
    'question' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const FlipCard = IDL.Record({ 'front' : IDL.Text, 'back' : IDL.Text });
  const InteractiveSurpriseConfig = IDL.Record({
    'quizQuestions' : IDL.Vec(QuizQuestion),
    'flipCards' : IDL.Vec(FlipCard),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'addLoveMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'addTimelineMilestone' : IDL.Func(
        [IDL.Text, Time, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
    'deleteLoveMessage' : IDL.Func([IDL.Text], [], []),
    'deleteTimelineMilestone' : IDL.Func([IDL.Text], [], []),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllLoveMessages' : IDL.Func([], [IDL.Vec(LoveMessage)], ['query']),
    'getAllTimelineMilestones' : IDL.Func(
        [],
        [IDL.Vec(TimelineMilestone)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFinalDedication' : IDL.Func([], [IDL.Opt(FinalDedication)], ['query']),
    'getInteractiveSurpriseConfig' : IDL.Func(
        [],
        [IDL.Opt(InteractiveSurpriseConfig)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setFinalDedication' : IDL.Func([FinalDedication], [], []),
    'setInteractiveSurpriseConfig' : IDL.Func(
        [InteractiveSurpriseConfig],
        [],
        [],
      ),
    'updateGalleryItemOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateLoveMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateLoveMessageOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateTimelineMilestone' : IDL.Func(
        [IDL.Text, Time, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateTimelineMilestoneOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };